#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[default_session]
startup_command = "vim -c :Files"
preview_command = "eza --all --git --icons --color=always --tree {}"

[[session]]
name = "main"
path = "~"
startup_command = "clear"
preview_command = "eza --all --git --icons --color=always --tree --level=1 {}"

[[session]]
name = "bash-config"
path = "~/dotfiles/bash"

[[session]]
name = "conda-config"
path = "~/dotfiles/conda"
startup_command = "vim .condarc"

[[session]]
name = "brew-config"
path = "~/dotfiles/brew/.config/homebrew-bundle"
startup_command = "vim Brewfile"

[[session]]
name = "git-config"
path = "~/dotfiles/git/.config/git"
startup_command = "vim config"

[[session]]
name = "starship-config"
path = "~/dotfiles/starship/.config"
startup_command = "vim starship.toml"

[[session]]
name = "tmux-config"
path = "~/dotfiles/tmux/.config/tmux"
startup_command = "vim tmux.conf"

[[session]]
name = "vim-config"
path = "~/dotfiles/vim/.vim"

[[session]]
name = "ssh-config"
path = "~/.ssh"
startup_command = "vim config"

[[session]]
name = "wiki"
path = "~/wiki"
startup_command = "vim index.md"

[[session]]
name = "sesh-config"
path = "~/dotfiles/sesh/.config/sesh"
startup_command = "vim sesh.toml"

