alias ll='ls -la'
alias l='ls'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
alias nvim-lazy='NVIM_APPNAME=nvim-lazy nvim'
alias nvim-kickstart='NVIM_APPNAME="nvim-kickstart" nvim'
alias nvim-minimax='NVIM_APPNAME="nvim-minimax" nvim'
