" vimrc

" Packages
runtime ftplugin/man.vim

packadd! matchit
packadd! justify

packadd! asyncomplete-lsp.vim
packadd! asyncomplete.vim
packadd! fzf
packadd! fzf.vim
packadd! gruvbox
packadd! vim-commentary
packadd! vim-dirvish
packadd! vim-fugitive
packadd! vim-lsp
packadd! vim-lsp-settings
packadd! vim-repeat
packadd! vim-sleuth
packadd! vim-surround
packadd! vim-unimpaired
packadd! wiki-ft.vim
packadd! wiki.vim

packadd! lightline.vim
packadd! vim-devicons

" auto filetype detection
filetype plugin indent on

