" vimrc

" vim-packages
runtime ftplugin/man.vim
packadd! matchit
packadd! justify

" junegunn/vim-plug
call plug#begin(has('nvim') ? stdpath('data') . '/vim-plug' : '~/.local/share/vim/vim-plug')

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'justinmk/vim-dirvish'
Plug 'mattn/vim-lsp-settings'
Plug 'morhetz/gruvbox'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'

Plug 'itchyny/lightline.vim'
Plug 'ryanoasis/vim-devicons'

call plug#end()

" auto filetype detection
filetype plugin indent on
